config/routes.rb
Rails.application.routes.draw do

  post '/lists/search' => 'lists#result'
  get '/lists/search' => 'lists#search'
  
  post '/lists/:list_id/tasks/:id/toggle', to: 'tasks#toggle', as: 'task_toggle'  
  resources :lists do
    resources :tasks, only: [:create, :destroy]
  end
  
  post '/lists/:list_id/tasks/:id/toggle' => 'tasks#toggle'  

  root 'lists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks

  def self.search(search)
    if search
      List.where(['title LIKE ?',"%#{search}%"])
    else
      List.all
    end
  end


  validates :title,
    presence: true,
    length: {maximum: 31, message:"ToDoリストの名称は30文字以内にしてください"},
    uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  def self.search(search)
    if search
      Task.where(['title LIKE ?',"%#{search}%"])
    else
      Task.all
    end
  end

  validates :title,
    presence: true,
    uniqueness: true,
    length: {maximum: 31, message:"ToDoリストの名称は30文字以内にしてください"}


  scope :finished, -> {where(done: true)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only:[:show, :edit, :update, :destroy]

  def index
    @lists = List.all.order('created_at DESC')
    @newList = List.new
    @tasks = Task.where("done = 0").order('deadline')
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to lists_path
    else
      render 'edit'
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  def search
    @lists = List.search(params[:search])
    @tasks = Task.search(params[:search])
  end

  def result
    @AllList = List.all
    @lists = List.where("title LIKE ?","%" + params[:search] + "%").order('created_at DESC')
    @tasks = Task.where("title LIKE ?","%" + params[:search] + "%").order('created_at DESC')
  end

  private
    def list_params
      params[:list].permit(:title)
    end

    def set_list
      @list = List.find(params[:id])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.create(tasks_params)
    redirect_to list_path(@list.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to list_path(params[:list_id])
  end

  def toggle
    @task = Task.find(params[:id])
    @task.done = !@task.done
    @task.save
    redirect_to list_path(params[:list_id])
  end

  def search
    @tasks = Task.search(params[:search])
  end

  private
    def tasks_params
      params[:task].permit(:title, :deadline)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to image_tag('logo.png', :size => "200x150"), '/' %>
    <%= link_to "検索", lists_search_path %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>

  <% if @list.errors.any? %>
    <%= @list.errors.messages[:title][0] %>
  <% end %>
</p>

<p>
  <%= f.submit %><br>
</p>

<% end %>
 

app/views/lists/_search_result.html.erb
<%if @tasks.count != 0 %>
  ToDoが<%= @tasks.count %>件見つかりました<br><br>
  <% @tasks.each do |task| %>
    <% @AllList.each do |list| %>
      <%if task.list_id == list.id %>
        <%= link_to task.title, list_path(list.id) %><br>
        <%= "期限：" %><%= task.deadline %><br>
        <%= "リスト："%><%= list.title %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= "作成日："%><%= task.created_at %><br>
      <% end %>
    <% end %>
  <% end %>
<% else %>
 <%="対象のToDoはありません"%>
<% end %>

<br><br><br>

<%if @lists.count != 0 %>
  ToDoリストが<%= @lists.count %>件見つかりました<br><br>
  <% @lists.each do |list| %>
    <%= link_to list.title, list_path(list.id) %><br>
    <%= list.created_at %><br>
  <% end %>
<% else %>
  <%="対象のToDoリストはありません"%>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/lists/index.html.erb
<p>新しいToDoリストを作成する</p>
<%= form_for @newList do |f| %>
  <p>
    <%= f.text_field :title %>
    <%= f.submit %><br><br>
  </p>
<% end %>

<ul>
  <% @lists.each do |list| %>
        <li>
          <%= link_to list.title, list_path(list.id) %><br>
          <%if list.tasks.count != 0 %>
              <%= list.tasks.count %>個中<%= list.tasks.finished.count %>個がチェック済み<br>
              <% @tasks.each do |task| %>
              <%if task.list_id == list.id %>
                ~<%= task.deadline %><br>
                <% break %>
              <% end %>
              <% end %>
          <% else %>
          ToDoがありません<br>
          <% end %>

          <%= link_to "[Edit]", edit_list_path(list.id) %>
        </li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1> Add </h1>

<%= render 'form' %>

app/views/lists/result.js.erb
$('#result').html(
  "<%= escape_javascript(render 'search_result') %>"
);

app/views/lists/search.html.erb
<h1> Search </h1>

<%= form_tag lists_search_path, action: :result, remote: true do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<ul id='result'></ul>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>

<ul>
  <% @list.tasks.each do |task| %>
  <li>
    <%= task.title %>
    <%= task.deadline %>
    <%= link_to "[Delete]",list_task_path(task.list_id, task.id), method: :delete, data: {confirm: "削除しますか？"} %>
    <% if task.done == false%>
      <%= button_to "未完了",task_toggle_path(task.list_id, task.id) %>
    <% else %>
      <%= button_to "完了",task_toggle_path(task.list_id, task.id) %>
    <% end %>
  </li>
  <% end %>

  <p>新しいToDoを作成する</p>
  <li>
    <%=form_for [@list, @list.tasks.build] do |f| %>
      <%= f.text_field :title %>
      <%= f.date_field :deadline %>
      <%= f.submit %>
    <% end %>
  </li>
  <% if @list.tasks.count == 0 %>
  登録されたToDoはございません
  <% end %>
</ul>